site_name: PMDM
site_url: https://albertincode.github.io/pmdm
theme:
  name: material
  logo: assets/logo.svg
  palette:
    primary: light green
  features:
    - navigation.instant
    - navigation.path
    - toc.follow
